### ISSUE TITLE
Select component: visually shifts when no value is inserted

### ISSUE THREAD

**Issue by vegardsoerlie** [fremtind/jokul#531]
**Describe the bug**
The select menu (underline and helptext) jumps up visually, so the chevron clips through the aforementioned elements.

**To Reproduce**

Run the example in the select-react package. Because the 1st and 4th select menus are connected, you can reproduce this behavior by:

1. Click on the 4th select menu
2. Click outside so it loses focus (do not choose a value)
3. Click on any other select menu to set focus on a new element.

The 1st select menu should now have jumped up because no value is selected and look like this:

![image](https://user-images.githubusercontent.com/14551408/69707070-4c3a1f00-10f9-11ea-9697-72116e251486.png)

**Expected behavior**

The select menu should not visually jump up when no value is selected.

**Comment by piofinn** [comment]
What happens here (under the hood) is that the value of the first select is set to `""` instead of `undefined`, which makes it remove the placeholder since it now strictly speaking has a value. The `""` value comes from the placeholder `<option>` element in the native `<select>` version, which cannot have an `undefined` value.

Hopefully this helps in finding a solution!
