### ISSUE TITLE
Text inputs examples

### ISSUE THREAD

**Issue by eduardodir** [fremtind/jokul#898]
**Is your feature request related to a problem? Please describe.**
I know there is some work on new text inputs, but the whole structure of this example page needs a refactoring.

**Describe the solution you'd like**
Some of the things I am expecting:
- It should be responsive and break nicely.
- Example options and examples should be in our example box and not standalone.
- A proper state implementation, not same mapping on all fields
- The input field of how much you earn, have a serious issue that you can write more than it is in the view length of the input field, it should stop or expand when there is no room left.
- No duplicate input labels, it should look more professional like a real example same goes for input subtexts.
- I would like to see a good error example, for example on a personalnumber validation.

**Additional context**
<img width="976" alt="Screenshot 2020-04-13 at 22 50 24" src="https://user-images.githubusercontent.com/56429532/79160264-c7b31900-7dd9-11ea-807b-43d50ca0b8f7.png">

**Comment by piofinn** [comment]
I've changed this example completely in my branch for new text inputs (#848 – sort of on hold because of new design changes, but should be taken up again). It should address most of these points, and will be implemented when we eventually merge the new fields. Maybe you can take a look and see if you have any comments? 😊
